ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea05f28>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea18240>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea05400>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea119e8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9a2cc0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8f9aa908>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9a83c8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0898>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d76d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0860>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0f28>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f76a0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74add8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74a518>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f7470>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74a5c0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74a860>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74aba8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0cf8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74fef0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74feb8>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c75e6d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0400>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea05898>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74a2b0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d0b38>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c741860>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763c50>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d09e8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea18400>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74fa58>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d7978>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d7b70>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648240>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d7940>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648e10>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d76d8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648438>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea11c50>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768b00>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6549b0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:discord.ext.tasks:Internal background task failed.
Traceback (most recent call last):
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samcodesign/.local/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 73, in _loop
    await self.coro(*args, **kwargs)
  File "app.py", line 28, in change_status
    await bot.change_presence(activity=discord.Game(next(status)))
  File "/home/samcodesign/.local/lib/python3.6/site-packages/discord/client.py", line 943, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
  File "/home/samcodesign/.local/lib/python3.6/site-packages/discord/gateway.py", line 512, in change_presence
    await self.send(sent)
  File "/home/samcodesign/.local/lib/python3.6/site-packages/discord/gateway.py", line 482, in send
    await super().send(data)
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/samcodesign/.local/lib/python3.6/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6cdbe0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c664d30>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6cdf28>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5cc1d0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c664438>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5d3470>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648be0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c75e630>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768780>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d99c2b0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c7689e8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768c50>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c7685f8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c654940>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768be0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea11cf8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea11dd8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763048>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74fc18>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763358>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c654a90>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea11748>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768c50>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c7636a0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c64ce80>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763f60>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6483c8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c600be0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5fa668>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c600908>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5fa2b0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5ccd68>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c600a20>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5dde48>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648668>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6cdfd0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5d30f0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c664048>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5efa58>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5fa320>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5e6fd0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea181d0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5ddf60>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5d3f60>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea18c18>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5d3518>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c64ca58>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c741cf8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c741b00>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c768438>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f7cc0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f7f98>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5efba8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f7e48>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d7f28>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea18588>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d75c0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763ac8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c594da0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea115f8>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c594f60>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea11b70>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6cdb38>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea114e0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5a8b38>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f7630>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b18d0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c64cdd8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b1908>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d7d30>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b7be0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b7710>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5dda90>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b75f8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c75e4a8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c72fef0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c547390>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5e65f8>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea0b940>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648240>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5e6860>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d04e0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c72fba8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c54cf98>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c54cba8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c54cb70>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5ddf60>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c648588>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5ef518>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c74ff98>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d99c710>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5ef828>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8e9f77b8>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c6cd748>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c559080>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5efcf8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c600940>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5e6ef0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c55f4a8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8ea4f470>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c54c940>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8d9d09e8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c55f668>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c568da0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c55f9e8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5bd8d0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c55f6d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5bd828>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b1a90>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5948d0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c763c50>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c594c18>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5946d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b16d8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c594b70>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faa8c5b1cf8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Marhaba , Bot is ready Captain.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb360668>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Can't keep up, websocket is 13.4s behind.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb394ba8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb360518>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb36c9e8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb379748>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb36cac8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa2fdd30>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a3128>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a3048>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a32b0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a3080>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb36ca58>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb379668>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fb365e10>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a3780>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8079b00>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8081550>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8081ba8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88b9908>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa302438>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88b96d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa302978>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa30af60>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a73c8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa302898>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88a7278>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43fa3026d8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8035630>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f88dbd30>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8081128>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
ERROR:asyncio:Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f43f8079d68>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Huh , Bot is ready Captain.
